Settings page added
team-envision/ManagementApp pull request #29
Opened 2024-09-26 14:21 UTC by Sayakd915

commit -m "Settings Page Added"

https://github.com/user-attachments/assets/33c5fce9-86e0-45bc-a734-447aa91fd8f5

fix #26

2024-09-29 08:48 UTC, SHREYANSHSK requested changes
make this small change after that i will merge the pr

2024-09-29 08:48 UTC, SHREYANSHSK commented on lib/app/modules/Settings/views/settings_view.dart
> +              children: [
give mainAxis alignment and make the page responsive such that no need to scroll this page

2024-10-15 10:31 UTC, Sayakd915 commented
commit -m "Settings Page Edited"

fix #7 


https://github.com/user-attachments/assets/1fd88263-f3a6-435f-9c3d-4cf175c6f539

2024-10-15 16:33 UTC, SHREYANSHSK approved these changes
merging the pr

2024-10-15 16:40 UTC, merged